layout_spectrum: 1
favicon: null
name: maladi
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 1
  lightness: 0.1527171735651791
  saturation: 0.4800855298526585
  rhythmicContrast: 0.3986258925870061
  brandColors:
    - '#FFFFFF'
    - '#9CDCFD'
    - '#696C70'
    - '#E2E1E2'
typography_spectrum: 0.4702128
