name: maladi
favicon: null
layout_spectrum: 0.2729954244568944
typography_spectrum: 0.6502038172911853
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#211f20'
    - '#575556'
    - '#b0b0b0'
    - '#72ca49'
  brandStrength: 0
  lightness: 0.1527171735651791
  saturation: 0.4800855298526585
  rhythmicContrast: 0.3986258925870061
purpose: []
