color:
  brandStrength: 1
  saturation: 0.4361702
  brandColors:
    - '#FFFFFF'
    - '#9CDCFD'
    - '#696C70'
    - '#E2E1E2'
  lightness: 0.4787234
  rhythmicContrast: 0.7255319
analytics:
  facebook: null
  google: null
  twitter: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
favicon: null
layout_spectrum: 1
purpose: []
name: maladi
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4702128
